apiVersion: v1
kind: Service
metadata:
  name: rails-service
  labels:
    app: kubecake
spec:
  type: LoadBalancer
  ports:
    - port: 80             
      targetPort: 3000      
      protocol: TCP         
  selector:
    app: kubecake 

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: postgres

---

apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: ClusterIP
  ports:
    - port: 6379
  selector:
    app: redis

---

apiVersion: v1
kind: Service
metadata:
  name: ollama-service
spec:
  type: ClusterIP
  ports:
    - port: 11434
  selector:
    app: ollama
