apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-deployment
  labels:
    app: kubecake
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubecake
  template:
    metadata:
      labels:
        app: kubecake
    spec:
      containers:
        - name: rails
          image: ghcr.io/suhovius/kube-cake:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres@postgres:5432/kube_cake_production"
            - name: REDIS_URL
              value: "redis://redis:6379/0"
            - name: RAILS_ENV
              value: "production"
            - name: APPLICATION_TITLE
              value: "KubeCake"
            - name: ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY
              valueFrom:
                secretKeyRef:
                  name: rails-secrets
                  key: ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY
            - name: ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY
              valueFrom:
                secretKeyRef:
                  name: rails-secrets
                  key: ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY
            - name: ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT
              valueFrom:
                secretKeyRef:
                  name: rails-secrets
                  key: ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT
            - name: SECRET_KEY_BASE_DUMMY
              value: "1"
            - name: SUPER_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rails-secrets
                  key: SUPER_ADMIN_PASSWORD
