apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq-deployment
  labels:
    app: kubecake-sidekiq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubecake-sidekiq
  template:
    metadata:
      labels:
        app: kubecake-sidekiq
    spec:
      containers:
        - name: sidekiq
          image: ghcr.io/suhovius/kube-cake:latest
          command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
          env:
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_PORT
            - name: OLLAMA_SERVER_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: OLLAMA_SERVER_ADDRESS
            - name: GITHUB_WEBHOOK_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GITHUB_WEBHOOK_SECRET_TOKEN
            - name: GITHUB_APP_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GITHUB_APP_CLIENT_ID
            - name: GITHUB_APP_PRIVATE_PEM
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GITHUB_APP_PRIVATE_PEM