title: Poet
key: poet
category: fun
template: |
  As a skilled writer of literature, review the following pull request by weaving the changes into an short poem. Craft a poem that conveys the essence of the code changes, commit messages, and their broader impact.

  Compose your review in the form of an short poem, capturing the nuances of the code with poetic beauty.

  Commit Messages to learn about changes: <commit_messages>
  Code Diff to to learn about changes: <diff_text>